/**
 * Optional one-shot asset + data fetcher.
 *
 *   npm run assets
 *
 * Pulls agent icons, weapon art, map thumbnails and — importantly — the
 * CURRENT weapon shop prices from valorant-api.com (a free community mirror
 * of Riot's own client data), then writes:
 *
 *   assets/agents/<agent>.png     picked up automatically by the overlay
 *   assets/weapons/<weapon>.png
 *   assets/maps/<map>.png
 *   data/gamedata.json            weapon prices + agent roster, merged over
 *                                 the built-in defaults on next server start
 *
 * The suite runs perfectly well without this — it just falls back to the
 * built-in silhouettes and the prices baked into server/gamedata.js.
 * Ability costs and ult-point requirements are not published anywhere, so
 * those keep the defaults; edit data/gamedata.json if a patch moves them.
 */

import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { DEFAULT_GAMEDATA } from '../server/gamedata.js';

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const API = 'https://valorant-api.com/v1';

const key = (s) => s.toLowerCase().replace(/[^a-z0-9]/g, '');

async function getJSON(url) {
  const r = await fetch(url);
  if (!r.ok) throw new Error(`${url} → ${r.status}`);
  return (await r.json()).data;
}

async function download(url, dest) {
  if (!url) return false;
  try {
    // Re-runs are cheap: art that's already on disk is left alone.
    await fs.access(dest);
    return true;
  } catch { /* not cached yet — fetch it */ }
  try {
    const r = await fetch(url);
    if (!r.ok) return false;
    await fs.mkdir(path.dirname(dest), { recursive: true });
    await fs.writeFile(dest, Buffer.from(await r.arrayBuffer()));
    return true;
  } catch { return false; }
}

async function main() {
  console.log('Fetching from valorant-api.com …\n');

  const [agents, weapons, maps] = await Promise.all([
    getJSON(`${API}/agents?isPlayableCharacter=true`),
    getJSON(`${API}/weapons`),
    getJSON(`${API}/maps`),
  ]);

  /* ---- agents ---- */
  const AGENTS = { ...DEFAULT_GAMEDATA.AGENTS };
  let agentImgs = 0;
  const estimated = [];
  for (const a of agents) {
    const k = key(a.displayName);
    // Ult points and ability costs are not in any API. Agents we have no
    // hand-checked values for get flagged so the panel can warn about them
    // instead of quietly showing a wrong ult meter on stream.
    const known = AGENTS[k];
    if (!known) estimated.push(k);
    AGENTS[k] = {
      ...(known || { ult: 7, abil: { c: 200, q: 200, e: 0 }, max: [2, 2, 1] }),
      role: a.role?.displayName || known?.role || '',
      label: a.displayName,
      ...(known ? {} : { estimated: true }),
    };
    if (await download(a.displayIcon, path.join(ROOT, 'assets', 'agents', `${k}.png`))) agentImgs++;
    // Full-body art for the agent-pick screen.
    if (await download(a.fullPortrait, path.join(ROOT, 'assets', 'agents', `${k}-full.png`))) agentImgs++;
  }
  console.log(`  agents  : ${agents.length} entries, ${agentImgs} icons`);
  if (estimated.length) {
    console.log(`            ⚠ no verified ult/ability values for: ${estimated.join(', ')}`);
    console.log('              edit data/gamedata.json before broadcasting.');
  }

  /* ---- weapons (live shop prices) ---- */
  const WEAPONS = { ...DEFAULT_GAMEDATA.WEAPONS };
  let weaponImgs = 0;
  for (const w of weapons) {
    const k = key(w.displayName);
    const cat = (w.category || '').split('::').pop().toLowerCase();
    const cls = { rifle: 'rifle', smg: 'smg', sniper: 'sniper', shotgun: 'shotgun',
                  sidearm: 'sidearm', heavy: 'heavy', melee: 'melee' }[cat] || 'rifle';
    WEAPONS[k] = {
      label: w.displayName,
      class: cls,
      price: w.shopData?.cost ?? WEAPONS[k]?.price ?? 0,
    };
    if (await download(w.displayIcon, path.join(ROOT, 'assets', 'weapons', `${k}.png`))) weaponImgs++;
  }
  console.log(`  weapons : ${weapons.length} entries, ${weaponImgs} icons`);

  /* ---- maps ---- */
  const MAPS = maps.filter((m) => m.tacticalDescription).map((m) => m.displayName).sort();
  let mapImgs = 0;
  for (const m of maps) {
    if (!m.tacticalDescription) continue;
    const k = key(m.displayName);
    // Thumbnail for lists, plus the tall splash art the veto screen crops.
    if (await download(m.listViewIcon || m.splash, path.join(ROOT, 'assets', 'maps', `${k}.png`))) mapImgs++;
    if (await download(m.splash, path.join(ROOT, 'assets', 'maps', `${k}-splash.png`))) mapImgs++;
  }
  console.log(`  maps    : ${MAPS.length} entries, ${mapImgs} images`);

  /* ---- write merged gamedata ---- */
  const out = {
    _note: 'Generated by npm run assets. Hand-edits survive re-runs only for keys the fetcher does not own (RULES, ability costs, ult points). Delete this file to fall back to server/gamedata.js defaults.',
    AGENTS, WEAPONS, MAPS,
    RULES: DEFAULT_GAMEDATA.RULES,
  };
  await fs.mkdir(path.join(ROOT, 'data'), { recursive: true });
  await fs.writeFile(path.join(ROOT, 'data', 'gamedata.json'), JSON.stringify(out, null, 2));

  console.log('\nWrote data/gamedata.json — restart the server to pick it up.');
}

main().catch((e) => {
  console.error('\nFetch failed:', e.message);
  console.error('No problem — the suite runs on its built-in defaults. Try again when you have a connection.');
  process.exit(1);
});
